// Code generated by protoc-gen-go. DO NOT EDIT.
// source: post/post.proto

package post

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9e4a9952ba66d64, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Post struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreateAt             string   `protobuf:"bytes,5,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	ModifiedAt           string   `protobuf:"bytes,6,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9e4a9952ba66d64, []int{1}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Post) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Post) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *Post) GetModifiedAt() string {
	if m != nil {
		return m.ModifiedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "post.Empty")
	proto.RegisterType((*Post)(nil), "post.Post")
}

func init() { proto.RegisterFile("post/post.proto", fileDescriptor_e9e4a9952ba66d64) }

var fileDescriptor_e9e4a9952ba66d64 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xcd, 0x4a, 0xc5, 0x30,
	0x10, 0x85, 0x6f, 0x6a, 0x7a, 0x7f, 0xa6, 0xa0, 0x30, 0xb8, 0x08, 0xd7, 0x85, 0x92, 0xcd, 0x75,
	0x55, 0x45, 0x9f, 0xa0, 0xa8, 0xb8, 0x15, 0xc5, 0xb5, 0xd4, 0x66, 0x84, 0x40, 0xdb, 0x84, 0x76,
	0x10, 0x7c, 0x13, 0x5f, 0xc3, 0x37, 0x94, 0x4c, 0x29, 0x74, 0xa7, 0x9b, 0x30, 0xe7, 0x3b, 0x27,
	0x24, 0x67, 0xe0, 0x24, 0x86, 0x91, 0xaf, 0xd2, 0x51, 0xc6, 0x21, 0x70, 0x40, 0x9d, 0x66, 0xbb,
	0x81, 0xfc, 0xa1, 0x8b, 0xfc, 0x65, 0xbf, 0x15, 0xe8, 0xa7, 0x30, 0x32, 0x22, 0xe8, 0xbe, 0xee,
	0xc8, 0xa8, 0x0b, 0x75, 0xb9, 0x7b, 0x96, 0x19, 0x8f, 0x21, 0xf3, 0xce, 0x64, 0x42, 0x32, 0xef,
	0xf0, 0x14, 0x72, 0xf6, 0xdc, 0x92, 0x39, 0x12, 0x34, 0x09, 0x34, 0xb0, 0x69, 0x42, 0xcf, 0xd4,
	0xb3, 0xd1, 0xc2, 0x67, 0x89, 0x67, 0xb0, 0x6b, 0x06, 0xaa, 0x99, 0xde, 0x6a, 0x36, 0xb9, 0x78,
	0xdb, 0x09, 0x54, 0x8c, 0xe7, 0x50, 0x74, 0xc1, 0xf9, 0x0f, 0x4f, 0x2e, 0xd9, 0x6b, 0xb1, 0x61,
	0x46, 0x15, 0xdf, 0xfc, 0x28, 0x28, 0xd2, 0xd7, 0x5e, 0x68, 0xf8, 0xf4, 0x0d, 0xe1, 0x01, 0xb6,
	0x8f, 0xc4, 0x89, 0x8c, 0x58, 0x94, 0x52, 0x49, 0x3a, 0xec, 0x61, 0x12, 0xc9, 0xb1, 0xab, 0x6b,
	0x85, 0x07, 0x80, 0x3b, 0x79, 0x45, 0x8a, 0x2d, 0xdc, 0xfd, 0xf2, 0x9a, 0x5d, 0xa5, 0xe0, 0x6b,
	0x74, 0xff, 0x0b, 0xde, 0x53, 0x4b, 0x7f, 0x06, 0xdf, 0xd7, 0xb2, 0xe4, 0xdb, 0xdf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x24, 0x2e, 0x9e, 0x4d, 0x77, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostServiceClient is the client API for PostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostServiceClient interface {
	// 必须要有input type, 如为空需要定义空的类型
	GetPosts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (PostService_GetPostsClient, error)
	CreatePost(ctx context.Context, in *Post, opts ...grpc.CallOption) (*Empty, error)
	UpdatePost(ctx context.Context, in *Post, opts ...grpc.CallOption) (*Empty, error)
	DeletePost(ctx context.Context, in *Post, opts ...grpc.CallOption) (*Empty, error)
}

type postServiceClient struct {
	cc *grpc.ClientConn
}

func NewPostServiceClient(cc *grpc.ClientConn) PostServiceClient {
	return &postServiceClient{cc}
}

func (c *postServiceClient) GetPosts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (PostService_GetPostsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PostService_serviceDesc.Streams[0], "/post.PostService/GetPosts", opts...)
	if err != nil {
		return nil, err
	}
	x := &postServiceGetPostsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PostService_GetPostsClient interface {
	Recv() (*Post, error)
	grpc.ClientStream
}

type postServiceGetPostsClient struct {
	grpc.ClientStream
}

func (x *postServiceGetPostsClient) Recv() (*Post, error) {
	m := new(Post)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *postServiceClient) CreatePost(ctx context.Context, in *Post, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/post.PostService/CreatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) UpdatePost(ctx context.Context, in *Post, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/post.PostService/UpdatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) DeletePost(ctx context.Context, in *Post, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/post.PostService/DeletePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostServiceServer is the server API for PostService service.
type PostServiceServer interface {
	// 必须要有input type, 如为空需要定义空的类型
	GetPosts(*Empty, PostService_GetPostsServer) error
	CreatePost(context.Context, *Post) (*Empty, error)
	UpdatePost(context.Context, *Post) (*Empty, error)
	DeletePost(context.Context, *Post) (*Empty, error)
}

func RegisterPostServiceServer(s *grpc.Server, srv PostServiceServer) {
	s.RegisterService(&_PostService_serviceDesc, srv)
}

func _PostService_GetPosts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PostServiceServer).GetPosts(m, &postServiceGetPostsServer{stream})
}

type PostService_GetPostsServer interface {
	Send(*Post) error
	grpc.ServerStream
}

type postServiceGetPostsServer struct {
	grpc.ServerStream
}

func (x *postServiceGetPostsServer) Send(m *Post) error {
	return x.ServerStream.SendMsg(m)
}

func _PostService_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Post)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.PostService/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).CreatePost(ctx, req.(*Post))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_UpdatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Post)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).UpdatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.PostService/UpdatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).UpdatePost(ctx, req.(*Post))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Post)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.PostService/DeletePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).DeletePost(ctx, req.(*Post))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "post.PostService",
	HandlerType: (*PostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePost",
			Handler:    _PostService_CreatePost_Handler,
		},
		{
			MethodName: "UpdatePost",
			Handler:    _PostService_UpdatePost_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _PostService_DeletePost_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetPosts",
			Handler:       _PostService_GetPosts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "post/post.proto",
}
