// Code generated by protoc-gen-go. DO NOT EDIT.
// source: post.proto

package post

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Post struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreateAt             string   `protobuf:"bytes,5,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	ModifiedAt           string   `protobuf:"bytes,6,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{1}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Post) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Post) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *Post) GetModifiedAt() string {
	if m != nil {
		return m.ModifiedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "post.Empty")
	proto.RegisterType((*Post)(nil), "post.Post")
}

func init() { proto.RegisterFile("post.proto", fileDescriptor_e114ad14deab1dd1) }

var fileDescriptor_e114ad14deab1dd1 = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8f, 0x3d, 0x6a, 0xc3, 0x40,
	0x10, 0x46, 0xb3, 0xca, 0xea, 0x6f, 0x04, 0x29, 0x86, 0x14, 0x4b, 0x52, 0x24, 0xa8, 0x49, 0x2a,
	0x61, 0x6c, 0x70, 0xaf, 0xc2, 0xb8, 0x35, 0xf6, 0x01, 0x8c, 0xac, 0x1d, 0xc3, 0x82, 0xa5, 0x15,
	0xd2, 0x60, 0xf0, 0x4d, 0x7c, 0x5c, 0xb3, 0x23, 0xd4, 0xcd, 0xf7, 0x5e, 0x33, 0x0f, 0x60, 0xf0,
	0x13, 0x57, 0xc3, 0xe8, 0xd9, 0xa3, 0x0e, 0x77, 0x99, 0x42, 0xbc, 0xeb, 0x06, 0x7e, 0x94, 0x4f,
	0x05, 0xfa, 0xe0, 0x27, 0x46, 0x04, 0xdd, 0x37, 0x1d, 0x19, 0xf5, 0xab, 0xfe, 0xf3, 0xa3, 0xdc,
	0xf8, 0x01, 0x91, 0xb3, 0x26, 0x12, 0x12, 0x39, 0x8b, 0x9f, 0x10, 0xb3, 0xe3, 0x1b, 0x99, 0x77,
	0x41, 0xf3, 0x40, 0x03, 0x69, 0xeb, 0x7b, 0xa6, 0x9e, 0x8d, 0x16, 0xbe, 0x4c, 0xfc, 0x86, 0xbc,
	0x1d, 0xa9, 0x61, 0x3a, 0x37, 0x6c, 0x62, 0x71, 0xd9, 0x0c, 0x6a, 0xc6, 0x1f, 0x28, 0x3a, 0x6f,
	0xdd, 0xd5, 0x91, 0x0d, 0x3a, 0x11, 0x0d, 0x0b, 0xaa, 0x79, 0xbd, 0x85, 0x22, 0x7c, 0x76, 0xa2,
	0xf1, 0xee, 0x5a, 0xc2, 0x3f, 0xc8, 0xf6, 0xc4, 0x81, 0x4c, 0x58, 0x54, 0x52, 0x24, 0x09, 0x5f,
	0x30, 0x8f, 0x60, 0xca, 0xb7, 0x95, 0xba, 0x24, 0x12, 0xba, 0x79, 0x05, 0x00, 0x00, 0xff, 0xff,
	0xf6, 0xa3, 0xa0, 0x62, 0xf6, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostServiceClient is the client API for PostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostServiceClient interface {
	// 必须要有input type, 如为空需要定义空的类型
	GetPosts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (PostService_GetPostsClient, error)
}

type postServiceClient struct {
	cc *grpc.ClientConn
}

func NewPostServiceClient(cc *grpc.ClientConn) PostServiceClient {
	return &postServiceClient{cc}
}

func (c *postServiceClient) GetPosts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (PostService_GetPostsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PostService_serviceDesc.Streams[0], "/post.PostService/GetPosts", opts...)
	if err != nil {
		return nil, err
	}
	x := &postServiceGetPostsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PostService_GetPostsClient interface {
	Recv() (*Post, error)
	grpc.ClientStream
}

type postServiceGetPostsClient struct {
	grpc.ClientStream
}

func (x *postServiceGetPostsClient) Recv() (*Post, error) {
	m := new(Post)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PostServiceServer is the server API for PostService service.
type PostServiceServer interface {
	// 必须要有input type, 如为空需要定义空的类型
	GetPosts(*Empty, PostService_GetPostsServer) error
}

func RegisterPostServiceServer(s *grpc.Server, srv PostServiceServer) {
	s.RegisterService(&_PostService_serviceDesc, srv)
}

func _PostService_GetPosts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PostServiceServer).GetPosts(m, &postServiceGetPostsServer{stream})
}

type PostService_GetPostsServer interface {
	Send(*Post) error
	grpc.ServerStream
}

type postServiceGetPostsServer struct {
	grpc.ServerStream
}

func (x *postServiceGetPostsServer) Send(m *Post) error {
	return x.ServerStream.SendMsg(m)
}

var _PostService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "post.PostService",
	HandlerType: (*PostServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetPosts",
			Handler:       _PostService_GetPosts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "post.proto",
}
